name: sonar-scanner

on:
  pull_request:
    branches:
    - master
  push: 
    branches: 
    - master
    - develope

jobs:
  SonarScanner:
    if: github.repository == 'BlizD/BPS'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: ''
    - run: |
        git fetch --prune --unshallow
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Setup SonarQube scanner
      uses: warchant/setup-sonar-scanner@v1
    - name: Run SonarQube on push
      if: github.event_name == 'push'
      run: sonar-scanner
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        -Dsonar.host.url=https://sonar.openbsl.ru
        -Dsonar.branch.name=${GITHUB_REF#refs/heads/}
        -Dsonar.bsl.languageserver.enabled=true
    - name: Run SonarQube on pull request
      if: github.event_name == 'pull_request'
      run: sonar-scanner
        -X
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        -Dsonar.host.url=https://sonar.openbsl.ru
        -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
        -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }}
        -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }}
        -Dsonar.bsl.languageserver.enabled=true
